[package]
name = "novadm"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.11.4", package = "gtk4" }
adw = { version = "0.9.2", package = "libadwaita" }
glib = "0.22.9"

futures-util = "0.3.34"
reqwest = { version = "0.13.4", features = ["stream"] }
tokio = { version = "1.53.1", features = ["full"] }
